# Site settings
title: Justin Chmura
email: justin.chmura@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Digital Resume
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justinchmura.github.io" # the base hostname & protocol for your site
twitter_username: justinchmura
github_username:  justinchmura

# Build settings
markdown: kramdown
